welcome = [
    "Kellemes napot Viktória hercegnő!",
    "Szia Borsó!",
    "Remélem nem fáj a pocikád.",
    "Szia!",
    "Sziaaa.",
    "Sziaaaa.",
    "Sziaaaaa.",
    "Ööö csá.",
    "Halóóó. ..  Zzzz. ..  Halóóó.",
    "Halóóó.",
    "Jó reggelt Kisborsó, örülök hogy felébredtél.",
    "Facebook üzenetek mentése... Ne kapcsold ki!",
    "Köszönöm hogy ma reggel kedves voltál!",
    "Szép napot!",
    "Szervusz.",
    "Heló.",
    "Hi.",
    "Szia cica.",
    "Mornin'",
    "Hey.",
    "Hogy vagyunk ezen a pompás reggelen?",
    "Szia szivecske.",
    "'Jajj itt a Cicuka.'",
    "Jó újra itt látni téged.",
    "Hé fordulj egy pillanatra balra ...  ez az, SZIA.",
    "Kk.",
    "Kk csá.",
    "szia.",
    "Sziasztok.",
    "Betöltött az alkalmazás, üdvözlégy!",
    "A királylány szolgálatában!",
    "Bonzsúr.",
    "Szépséges estét hölgyem!",
    "Kellemes délutánt kisasszony!"
]

comment = [
    "Légyszíves ne felejts el reggelizni.",
    "E heti alkalmazás indításunk nyertese pedig: Viktória!",
    "Jól áll a hajad.",
    "Tetszik ez a nadrág.",
    "Nem fázol?",
    "Tessék menni aludni, szép álmokat Borsócska.",
    "Nincs meleged?",
    "Igyál egy pohár vizet",
    "Főzzek neked teát?",
    "Mikor fogunk összeházasodni?",
    "Kérek szépen egy puszit.",
    "Megyek főzök pesztóstésztát.",
    "Kellene megint menni az IKEA-ba.",
    "Nem vagy álmoska?",
    "Gyere aludni jó? Alvááás.",
    "Gyere ide gyöngyike. ... PURRR.",
    "Naaa, nézz már oda!",
    "Fantasztikus, tényleg.",
    "Ah, megint dolgoznod kell?",
    "Túl sok időt ne tölts itt!",
    "De aranyos vagy hogy megsimogatsz!",
    "Gyere aludni.",
    "Jössz aludni?",
    "Alvááás.",
    "Megsimogattad ma már a cicát?",
    "Mikor megyünk már moziba?",
    "Szeretném ha figyelnél a hasikádra és nem ennél sokat.",
    "Miért dolgozol ilyenkor?!",
    "Ne fáradj el légyszives, nyomogasd meg a szemed.",
    "Gyönyörű szép vagy ma!",
    "Gyönyörű szép vagy ma! ... És máskor is!",
    "Csodaszép vagy ám.",
    "Mit fogsz ma ebédelni?",
    "Nem kérsz egy kávét? Sütit? Valamit?",
    "Ne legyél ma goromba, jó?",
    "Hová akarsz legközelebb elutazni?",
    "Mit csinálunk a hétvégén?",
    "Mikor vili?",
    "Tetszik a fölsőd.",
    "Hé nem jössz ide?..",
    "Na.",
    "Nagyon cuki amikor kirakod a fogacskádat.",
    "Klip-klap-klip-klap.. Prrrr.",
    "MAU. ... MAU. Ma..khmskas..u."
]

fun = ["😍", "😙", "😀", "😆", "😄", "😂", "😊", "🙂", "😁", "😱", "😘", "😚", "😍", "😝", "🤑", "😛", "😇", "😎", "😏",
       "❤", "😴", "😺", "😸", "😹", "😻", "😼", "😽", "🙀", "😿", "😾", "🐱", "🍵", "☕", "🙏", "🙈", "🙉", "🙊", "🙃",
       "🤖", "🤗", "🤘", "🤙", "🤞", "🤷", "💰", "👽", "💛", "💙", "💜", "❤", "💚", "💓", "💗", "💕", "💞", "💘", "💖",
       "✨", "⭐", "🌟", "💫", "🎵", "🔥"]

sad = [""]